version: '3.9'
services:
  crm-backend:
    container_name: crm-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
    networks:
      - crm-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - JWT_SECRET=secret
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0.0
    container_name: mongodb
    volumes:
      - ./init-mongodb:/docker-entrypoint-initdb.d
      - ./init-mongodb/data:/tmp/data
    networks:
      - crm-network
    ports:
      - 27017:27017
    restart: unless-stopped
networks:
  crm-network: